/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClassModify;
import controller.FacultyModify;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.FacultyModel;
import model.ClassinFaculty;
import model.DBConnection;

/**
 *
 * @author Quoc
 */
public class ClassFaculty extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchStudent
     */
    DefaultTableModel tableModel1;
    DefaultTableModel tableModel2;
    List<FacultyModel> facultyList = new ArrayList<>();
    List<ClassinFaculty> classList = new ArrayList<>();
    Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    public ClassFaculty() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        tableModel1 = (DefaultTableModel) tbFaculty.getModel();
        tableModel2 = (DefaultTableModel) tbClass.getModel();
        showFaculty();
        showClass();
        fillInComboBox();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAddStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClass = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFaculty = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        tfFacultyName = new javax.swing.JTextField();
        tfFacultyID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfClassID = new javax.swing.JTextField();
        tfClassName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbFacultyID = new javax.swing.JComboBox<>();
        btnSearchFaculty = new javax.swing.JButton();
        btnAddFaculty = new javax.swing.JButton();
        btnUpdateFaculty = new javax.swing.JButton();
        btnDeleteFaculty = new javax.swing.JButton();
        btnSearchClass = new javax.swing.JButton();
        btnAddClass = new javax.swing.JButton();
        btnUpdateClass = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1050, 470));
        getContentPane().setLayout(null);

        pnAddStudent.setBackground(new java.awt.Color(255, 255, 255));
        pnAddStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnAddStudent.setPreferredSize(new java.awt.Dimension(1008, 473));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Faculty/Class");

        tbClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class", "Class Name", "Faculty ID"
            }
        ));
        tbClass.setGridColor(new java.awt.Color(255, 255, 255));
        tbClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbClassMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbClass);
        if (tbClass.getColumnModel().getColumnCount() > 0) {
            tbClass.getColumnModel().getColumn(0).setResizable(false);
            tbClass.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbClass.getColumnModel().getColumn(1).setResizable(false);
        }

        tbFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Faculty ID", "Faculty Name", "Contact"
            }
        ));
        tbFaculty.setGridColor(new java.awt.Color(255, 255, 255));
        tbFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbFacultyMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbFaculty);
        if (tbFaculty.getColumnModel().getColumnCount() > 0) {
            tbFaculty.getColumnModel().getColumn(0).setResizable(false);
            tbFaculty.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbFaculty.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Faculty"));

        jLabel3.setText("Faculty Name");

        jLabel4.setText("Faculty ID");

        jLabel15.setText("Contact");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Class"));

        jLabel5.setText("Class Name");

        jLabel6.setText("Class ID");

        tfClassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClassIDActionPerformed(evt);
            }
        });

        jLabel7.setText("Faculty_id");

        cbFacultyID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfClassID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnSearchFaculty.setText("Search");
        btnSearchFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFacultyActionPerformed(evt);
            }
        });

        btnAddFaculty.setText("Add");
        btnAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFacultyActionPerformed(evt);
            }
        });

        btnUpdateFaculty.setText("Update");
        btnUpdateFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFacultyActionPerformed(evt);
            }
        });

        btnDeleteFaculty.setText("Delete");
        btnDeleteFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFacultyActionPerformed(evt);
            }
        });

        btnSearchClass.setText("Search");
        btnSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClassActionPerformed(evt);
            }
        });

        btnAddClass.setText("Add");
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });

        btnUpdateClass.setText("Update");
        btnUpdateClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateClassActionPerformed(evt);
            }
        });

        btnDeleteClass.setText("Delete");
        btnDeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAddStudentLayout = new javax.swing.GroupLayout(pnAddStudent);
        pnAddStudent.setLayout(pnAddStudentLayout);
        pnAddStudentLayout.setHorizontalGroup(
            pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddStudentLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnAddStudentLayout.createSequentialGroup()
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddStudentLayout.createSequentialGroup()
                        .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddStudentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        pnAddStudentLayout.setVerticalGroup(
            pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddStudentLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSearchFaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateFaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteFaculty))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteClass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnAddStudent);
        pnAddStudent.setBounds(0, 0, 1008, 473);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showFaculty() {
       facultyList = FacultyModify.findAll();
       tableModel1.setRowCount(0);
       facultyList.forEach((faculty) -> {
            tableModel1.addRow(new Object[] {faculty.getId(), faculty.getFacultyName(),faculty.getContact()});
        });
    }
    private void showClass() {
        classList = ClassModify.findAll();
       tableModel2.setRowCount(0);
       classList.forEach((classinfaculty) -> {
            tableModel2.addRow(new Object[] {classinfaculty.getId(), classinfaculty.getClassName(),classinfaculty.getFacultyID()});
        });

    }
     private void fillInComboBox(){
        try {
            
        conn = DBConnection.connect();
            pst = conn.prepareStatement("SELECT DISTINCT Faculty_id from faculty");
            rs= pst.executeQuery();
        while (rs.next()) {
                String name = rs.getString("Faculty_id");
                cbFacultyID.addItem(name);
            }
        } catch (Exception e) {
        }
    }
    private void btnSearchFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFacultyActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tfFacultyID.getText().trim());
        String sname = tfFacultyName.getText().toLowerCase().trim();
        FacultyModel fa = new FacultyModel(id, ABORT, sname);
        
            facultyList = FacultyModify.search(fa);
        
        
        tableModel1.setRowCount(0);
       facultyList.forEach((faculty) -> {
            tableModel1.addRow(new Object[] {faculty.getId(), faculty.getFacultyName(),faculty.getContact()});
        });
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Faculty must not empty");
        }
    }//GEN-LAST:event_btnSearchFacultyActionPerformed

    private void btnSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClassActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfClassID.getText().toLowerCase().trim();
        String sname = tfClassName.getText().toLowerCase().trim();
        ClassinFaculty cl = new ClassinFaculty(id, sname, ALLBITS);
        classList = ClassModify.search(cl);
       tableModel2.setRowCount(0);
       classList.forEach((classinfaculty) -> {
            tableModel2.addRow(new Object[] {classinfaculty.getId(), classinfaculty.getClassName(),classinfaculty.getFacultyID()});
        });
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_btnSearchClassActionPerformed

    private void tfClassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClassIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClassIDActionPerformed

    private void tbFacultyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFacultyMousePressed
        // TODO add your handling code here:
        int i = tbFaculty.getSelectedRow();
        tfFacultyID.setText(tableModel1.getValueAt(i, 0).toString());
        tfFacultyName.setText(tableModel1.getValueAt(i, 1).toString());
        tfContact.setText(tableModel1.getValueAt(i, 2).toString());
        
    }//GEN-LAST:event_tbFacultyMousePressed

    private void tbClassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClassMousePressed
        // TODO add your handling code here:
        int i = tbClass.getSelectedRow();
        tfClassID.setText(tableModel2.getValueAt(i, 0).toString());
        tfClassName.setText(tableModel2.getValueAt(i, 1).toString());
        cbFacultyID.setSelectedItem(tableModel2.getValueAt(i, 2).toString());
        
    }//GEN-LAST:event_tbClassMousePressed

    private void btnAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFacultyActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tfFacultyID.getText());
        String sname = tfFacultyName.getText();
        int contact = Integer.parseInt(tfContact.getText());
        FacultyModel fa = new FacultyModel(id, contact, sname);
        FacultyModify.insert(fa);        
        showFaculty();
        } catch (HeadlessException | NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please fill in all field! Can not empty! ");}
        catch (Exception ex) {
        }
    }//GEN-LAST:event_btnAddFacultyActionPerformed

    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfClassID.getText();
        String sname = tfClassName.getText();
        int facultyid = Integer.parseInt(cbFacultyID.getSelectedItem().toString());
        ClassinFaculty cl = new ClassinFaculty(id, sname, facultyid);
        ClassModify.insert(cl);        
        showClass();
        }catch (HeadlessException | NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please fill in all field! Can not empty! ");} catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddClassActionPerformed

    private void btnUpdateFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFacultyActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tfFacultyID.getText());
        String sname = tfFacultyName.getText();
        int contact = Integer.parseInt(tfContact.getText());
        FacultyModel fa = new FacultyModel(id, contact, sname);
        FacultyModify.update(fa);        
        showFaculty();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Fill in all fields");
        }
    }//GEN-LAST:event_btnUpdateFacultyActionPerformed

    private void btnUpdateClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClassActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfClassID.getText();
        String sname = tfClassName.getText();
        int facultyid = Integer.parseInt(cbFacultyID.getSelectedItem().toString());
        ClassinFaculty cl = new ClassinFaculty(id, sname, facultyid);
        ClassModify.update(cl);        
        showClass();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Fill in all fields");
        }
    }//GEN-LAST:event_btnUpdateClassActionPerformed

    private void btnDeleteFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFacultyActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tbFaculty.getSelectedRow();
        if(selectedIndex >= 0) {
            FacultyModel fa = facultyList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
            System.out.println("option : " + option);

            if(option == 0) {
                FacultyModify.delete(fa.getId());

                showFaculty();
            }
        }
    }//GEN-LAST:event_btnDeleteFacultyActionPerformed

    private void btnDeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClassActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tbClass.getSelectedRow();
        if(selectedIndex >= 0) {
            ClassinFaculty cl = classList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
            System.out.println("option : " + option);

            if(option == 0) {
                ClassModify.delete(cl.getId());

                showClass();
            }
        }
    }//GEN-LAST:event_btnDeleteClassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnAddFaculty;
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnDeleteFaculty;
    private javax.swing.JButton btnSearchClass;
    private javax.swing.JButton btnSearchFaculty;
    private javax.swing.JButton btnUpdateClass;
    private javax.swing.JButton btnUpdateFaculty;
    private javax.swing.JComboBox<String> cbFacultyID;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnAddStudent;
    private javax.swing.JTable tbClass;
    private javax.swing.JTable tbFaculty;
    private javax.swing.JTextField tfClassID;
    private javax.swing.JTextField tfClassName;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfFacultyID;
    private javax.swing.JTextField tfFacultyName;
    // End of variables declaration//GEN-END:variables
}
