/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Subjects;
import controller.SubjectsModify;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.DBConnection;
/**
 *
 * @author Quoc
 */
public class Subject extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchStudent
     */
    DefaultTableModel tableModel;
    List<Subjects> subjectsList = new ArrayList<>();
    Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    public Subject() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        tableModel = (DefaultTableModel) tb.getModel();
        showSubjects();
        fillInComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAddStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfFees2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbCredit2 = new javax.swing.JComboBox<>();
        tfCode2 = new javax.swing.JTextField();
        tfSubject2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1050, 470));
        getContentPane().setLayout(null);

        pnAddStudent.setBackground(new java.awt.Color(255, 255, 255));
        pnAddStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnAddStudent.setPreferredSize(new java.awt.Dimension(1008, 473));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Subjects");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject ID", "Subject", "Credit", "Fees"
            }
        ));
        tb.setGridColor(new java.awt.Color(255, 255, 255));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(2).setResizable(false);
            tb.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Course detail"));

        jLabel9.setText("Subject");

        jLabel10.setText(" Code");

        jLabel11.setText("Fees");

        tfFees2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFees2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Credit");

        cbCredit2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cbCredit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCredit2ActionPerformed(evt);
            }
        });

        tfCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCode2ActionPerformed(evt);
            }
        });

        tfSubject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubject2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFees2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCredit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFees2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnAddStudentLayout = new javax.swing.GroupLayout(pnAddStudent);
        pnAddStudent.setLayout(pnAddStudentLayout);
        pnAddStudentLayout.setHorizontalGroup(
            pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
            .addGroup(pnAddStudentLayout.createSequentialGroup()
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnAddStudentLayout.setVerticalGroup(
            pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddStudentLayout.createSequentialGroup()
                .addGroup(pnAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(pnAddStudentLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(pnAddStudent);
        pnAddStudent.setBounds(0, 0, 1008, 473);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showSubjects() {
        subjectsList = SubjectsModify.findAll();
        
        tableModel.setRowCount(0);
        subjectsList.forEach((subjects) -> {
            tableModel.addRow(new Object[] {subjects.getId(), subjects.getName(),subjects.getCredit(),subjects.getFee()
                    });
        });

    }
    private void fillInComboBox(){
        try {
            
        conn = DBConnection.connect();
            pst = conn.prepareStatement("SELECT DISTINCT Credit from subjects");
            rs= pst.executeQuery();
        while (rs.next()) {
                String name = rs.getString("Credit");
                cbCredit2.addItem(name);
            }
        } catch (Exception e) {
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfCode2.getText();
        String sname = tfSubject2.getText();
        float credit = Float.parseFloat(cbCredit2.getSelectedItem().toString());
        float fee = Float.parseFloat(tfFees2.getText());
        Subjects sb = new Subjects(id, sname, credit, fee);
        SubjectsModify.insert(sb);        
        showSubjects();
        } catch (HeadlessException | NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please fill in all field! Can not empty! ");
        }catch (Exception ex){
            //JOptionPane.showMessageDialog(null, "ID is exist");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfFees2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFees2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFees2ActionPerformed

    private void tfCode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCode2ActionPerformed

    private void tfSubject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubject2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfCode2.getText();
        String sname = tfSubject2.getText();
        float credit = Float.parseFloat(cbCredit2.getSelectedItem().toString());
        float fee = Float.parseFloat(tfFees2.getText().toString());
        Subjects sb = new Subjects(id, sname, credit, fee);
        SubjectsModify.update(sb);
        JOptionPane.showMessageDialog(null, "Updated sucessfully");
        showSubjects();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Fill in all fields");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbCredit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCredit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCredit2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tb.getSelectedRow();
        if(selectedIndex >= 0) {
            Subjects sb = subjectsList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
            System.out.println("option : " + option);

            if(option == 0) {
                SubjectsModify.delete(sb.getId());

                showSubjects();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String id = tfCode2.getText().toLowerCase().trim();
        String sname = tfSubject2.getText().toLowerCase().trim();
        Subjects sb = new Subjects(id, sname, ABORT, ABORT);
        subjectsList= SubjectsModify.search(sb);
        tableModel.setRowCount(0);
        subjectsList.forEach((subjects) -> {
            tableModel.addRow(new Object[] {subjects.getId(), subjects.getName(),subjects.getCredit(),subjects.getFee()
                    });
        });
        } catch (NumberFormatException e) {
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMousePressed
        // TODO add your handling code here:
        int i = tb.getSelectedRow();
        tfCode2.setText(tableModel.getValueAt(i, 0).toString());
        tfSubject2.setText(tableModel.getValueAt(i, 1).toString());
        cbCredit2.setSelectedItem(tableModel.getValueAt(i, 2).toString());
        tfFees2.setText(tableModel.getValueAt(i, 3).toString());
        
    }//GEN-LAST:event_tbMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCredit2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAddStudent;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tfCode2;
    private javax.swing.JTextField tfFees2;
    private javax.swing.JTextField tfSubject2;
    // End of variables declaration//GEN-END:variables
}
